// The palette. Every color in the artwork and on ijosh.com is defined here and nowhere
// else. Generates tokens.css, which the site imports.

// The mark's tones, as src/marks.mjs paints them.
export const T = {
  charcoal: '#17191c', offwhite: '#f4f7fb',
  mutedOnLight: '#666666', mutedOnDark: '#9c9ea2',
  resumeInk: '#414141', resumeGrey: '#999999',
};

// The banner field's four tones, an even ramp on charcoal. The brightest is the mark's own off-white.
export const FIELD = [T.offwhite, '#a8adb5', '#767b82', '#4a4f56'];

// The dark surface is the icon tile's charcoal and the dark text the mark's off-white.
const SITE = {
  light: {
    '--bg': '#ffffff',
    '--text': '#333333',
    '--icon': '#000000',
    '--text-muted': '#6b7280',
    '--text-body': '#4b5563',
    '--accent': '#ca486d',
    '--pill-bg': 'rgba(51, 51, 51, 0.1)',
    '--btn-bg': '#1c1c1c',
    '--btn-fg': '#ffffff',
  },
  dark: {
    '--bg': T.charcoal,
    '--text': T.offwhite,
    '--icon': T.offwhite,
    '--text-muted': '#9aa7b4',
    '--text-body': '#c6d0da',
    '--accent': '#e98aa3',
    '--pill-bg': 'rgba(255, 255, 255, 0.1)',
    '--btn-bg': T.offwhite,
    '--btn-fg': '#14171c',
  },
};

const MARK = {
  light: { '--mark': T.charcoal, '--mark-muted': T.mutedOnLight },
  dark: { '--mark': T.offwhite, '--mark-muted': T.mutedOnDark },
};

const vars = (obj, pad) =>
  Object.entries(obj)
    .map(([k, v]) => `${pad}${k}: ${v};`)
    .join('\n');

const scheme = (name, pad) =>
  [
    `${pad}color-scheme: ${name};`,
    vars(SITE[name], pad),
    `${pad}/* the mark on a ${name} surface */`,
    vars(MARK[name], pad),
  ].join('\n');

export const css = `/* The palette for ijosh.com. Generated by src/tokens.mjs: run \`task build\`, do not edit.
   Set data-theme="light" or "dark" on <html> to override the system preference. */
:root {
${scheme('light', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${scheme('dark', '    ')}
  }
}

:root[data-theme="dark"] {
${scheme('dark', '  ')}
}
`;
