// Generates tokens.css, the palette. Every color ijosh.com paints is defined here and
// nowhere else; the site imports these tokens and keeps no copy of its own, so a change
// lands here and reaches it the way a redraw of the mark reaches every README.
//
// The mark's two tones are not restated even here. src/marks.mjs draws them into every
// file in mark/, and they are read from it, so the stylesheet cannot name a tone the
// artwork does not use.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { T } from './marks.mjs';

// The charcoal and the off-white are named here because the site's dark surface is
// deliberately the same charcoal the icon tile is drawn on, and its dark text the same
// off-white as the mark. They move together or the icons stop sitting flush on the page.
const SITE = {
  light: {
    '--bg': '#ffffff',
    '--text': '#333333',
    '--icon': '#000000',
    '--text-muted': '#6b7280',
    '--text-body': '#4b5563',
    '--accent': '#ca486d',
    '--pill-bg': 'rgba(51, 51, 51, 0.1)',
    '--btn-bg': '#1c1c1c',
    '--btn-fg': '#ffffff',
  },
  dark: {
    '--bg': T.charcoal,
    '--text': T.offwhite,
    '--icon': T.offwhite,
    '--text-muted': '#9aa7b4',
    '--text-body': '#c6d0da',
    '--accent': '#e98aa3',
    '--pill-bg': 'rgba(255, 255, 255, 0.1)',
    '--btn-bg': T.offwhite,
    '--btn-fg': '#14171c',
  },
};

// Not a copy: these are the two tones marks.mjs paints into the artwork.
const MARK = {
  light: { '--mark': T.charcoal, '--mark-muted': T.mutedOnLight },
  dark: { '--mark': T.offwhite, '--mark-muted': T.mutedOnDark },
};

const vars = (obj, pad) =>
  Object.entries(obj)
    .map(([k, v]) => `${pad}${k}: ${v};`)
    .join('\n');

const scheme = (name, pad) =>
  [
    `${pad}color-scheme: ${name};`,
    vars(SITE[name], pad),
    `${pad}/* the mark on a ${name} surface */`,
    vars(MARK[name], pad),
  ].join('\n');

const css = `/* The palette. Every color ijosh.com paints is defined here; consumers
   import these tokens and keep no copy of their own. Generated by src/tokens.mjs, so run
   \`task build\` rather than editing this file. The mark's two tones come from
   src/marks.mjs and cannot drift from the artwork it draws. */
:root {
${scheme('light', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root {
${scheme('dark', '    ')}
  }
}
`;

// output directory from argv, default the repository root
const root = process.argv[2] ?? fileURLToPath(new URL('..', import.meta.url));
writeFileSync(join(root, 'tokens.css'), css);
console.log(`wrote tokens.css to ${root}`);
